package com.isoft.test;
// Generated 2016-4-18 14:23:37 by Hibernate Tools 3.5.0.Final

/**
 * TProduct generated by hbm2java
 */
public class TProduct implements java.io.Serializable {

	private String TProductId;
	private String TProductName;
	private String TProductType;
	private String TDiscount;
	private String TImgUrl;
	private String TBrand;
	private String TPrice;
	private String TInfo;

	public TProduct() {
	}

	public TProduct(String TProductId) {
		this.TProductId = TProductId;
	}

	public TProduct(String TProductId, String TProductName, String TProductType, String TDiscount, String TImgUrl,
			String TBrand, String TPrice, String TInfo) {
		this.TProductId = TProductId;
		this.TProductName = TProductName;
		this.TProductType = TProductType;
		this.TDiscount = TDiscount;
		this.TImgUrl = TImgUrl;
		this.TBrand = TBrand;
		this.TPrice = TPrice;
		this.TInfo = TInfo;
	}

	public String getTProductId() {
		return this.TProductId;
	}

	public void setTProductId(String TProductId) {
		this.TProductId = TProductId;
	}

	public String getTProductName() {
		return this.TProductName;
	}

	public void setTProductName(String TProductName) {
		this.TProductName = TProductName;
	}

	public String getTProductType() {
		return this.TProductType;
	}

	public void setTProductType(String TProductType) {
		this.TProductType = TProductType;
	}

	public String getTDiscount() {
		return this.TDiscount;
	}

	public void setTDiscount(String TDiscount) {
		this.TDiscount = TDiscount;
	}

	public String getTImgUrl() {
		return this.TImgUrl;
	}

	public void setTImgUrl(String TImgUrl) {
		this.TImgUrl = TImgUrl;
	}

	public String getTBrand() {
		return this.TBrand;
	}

	public void setTBrand(String TBrand) {
		this.TBrand = TBrand;
	}

	public String getTPrice() {
		return this.TPrice;
	}

	public void setTPrice(String TPrice) {
		this.TPrice = TPrice;
	}

	public String getTInfo() {
		return this.TInfo;
	}

	public void setTInfo(String TInfo) {
		this.TInfo = TInfo;
	}

}
